[theme]
primaryColor = "#0A66C2"
backgroundColor = "#F3F2EF"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#191919"
font = "sans serif"

[server]
headless = true
port = 8501
enableXsrfProtection = true

[browser]
gatherUsageStats = false
